### ISSUE TITLE
Fix maven site

### ISSUE THREAD

**Issue by agawda** [agawda/HAL9000#7]
mvn site generates errors - probably because of spring boot

**Comment by mprtcz** [comment]
Can you specify where the errors occured and what was the message?
I run the pom from your branch on travis-integration and the site went through without any errors.

**Comment by agawda** [comment]
https://gist.github.com/agawda/8bc48ea18372fd124428bb3085bfc28a
The reports were generated, but this thing appears and it's annoying.

**Comment by mprtcz** [comment]
Ok I se them now in my code as well, they were lost in all the downloading messages.
